trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterSdkPath: '/usr/local/flutter'
  flutterVersion: '2.2.3'  # Replace with the desired Flutter version

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get install -y curl git unzip

      # Download Flutter SDK
      curl -sSL https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_${flutterVersion}-stable.tar.xz -o flutter.tar.xz

      # Extract Flutter SDK
      mkdir -p $flutterSdkPath
      tar xf flutter.tar.xz -C $flutterSdkPath

      # Add Flutter to PATH
      echo "export PATH=$flutterSdkPath/bin:$PATH" >> ~/.bashrc
      source ~/.bashrc

      # Run Flutter doctor to verify installation
      flutter doctor
    displayName: 'Install Flutter SDK'
