# Flutter build
variables:
  projectDirectory: sample_project

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    stages:
      - stage: Install
        displayName: 'Install Dependencies'
        jobs:
          - job: Install
            displayName: 'Install Flutter Dependencies'
            steps:
            - task: UseFlutterVersion@0
              inputs:
                flutterVersion: 'stable'
            - script: flutter pub get
              displayName: 'Install Flutter dependencies'
